name: tutvideo
description: A new Flutter application.

version: 0.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dio: ^4.0.4
  downloads_path_provider_28: ^0.1.2
  dropdown_button2: ^1.4.0
  dropdown_search: ^3.0.1
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.3
  flutter_login: ^3.2.0
  flutter_widget_from_html: ^0.8.5
  font_awesome_flutter: ^9.2.0
  hive: ^2.0.6
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^9.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  flutter_test:
    sdk: flutter
flutter_app_name:
  name: "Palm Oasis Travel"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
